# Generated by Django 5.1.2 on 2024-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resim',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
