# Generated by Django 5.1.2 on 2024-10-26 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0002_alter_etkinlik_id_alter_kategori_id_alter_resim_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='baslangic_tarihi',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='bitis_tarihi',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='saat',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
